### ISSUE TITLE
Give implementation of queue and stack without STL in python,java

### ISSUE THREAD

**Issue by MananOO12** [ISTE-VIT/hacktoberfest-2020#26]
Linear implementation of stack and queue can be given without the use of STL. It would be better for beginner's to understand.
Also give their implementation using Linked List 
Programming Languages:
Python
Java
C

**Comment by umangagarwal11** [comment]
We are accepting codes from active users like yourself.
Feel free to contribute whatever you feel is necessary through pull requests :)
