### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by AakashBelide** [ISTE-VIT/hacktoberfest-2020#5]
This hacktoberfest, contribute to open source!
Kindly follow the guidelines or else your PR will be marked as invalid.
First timers are welcome!

**Comment by TheUltimateRythimGamer** [comment]
Hi, how I can help u?

**Comment by AakashPanda** [comment]
Im Adding the name

**Comment by umangagarwal11** [comment]
We have updated the readme with how to contribute 
Do check it out


> Hi, how I can help u?



> Im Adding the name

**Comment by satyabansahoo2000** [comment]
@umangagarwal11 @AakashBelide I wish to add DSA using GoLang. There are no repo for golang.

**Comment by umangagarwal11** [comment]
> @umangagarwal11 @AakashBelide I wish to add DSA using GoLang. There are no repo for golang. 

You can add folders as mentioned in the readme. :)

**Comment by satyabansahoo2000** [comment]
Added Sorting Methods using GoLang. [#20 ](https://github.com/ISTE-VIT/hacktoberfest-2020/pull/20)
Please check and let me know if any changes need to be done.

**Comment by AakashBelide** [comment]
Kindly mention the following while making a PR.
Mention the problem type along with subcategory and the programming language.
If the PR is not in the right format, it will not be merged and marked as invalid.
Kindly adhere to the rules.
Don't make any changes to the folders in the repo unless you want to add a new folder for the missing topic.

**Comment by ImKeelan** [comment]
Hi can I be assigned please if so, how can I help?

**Comment by satyabansahoo2000** [comment]
> Kindly mention the following while making a PR.
> Mention the problem type along with subcategory and the programming language.
> If the PR is not in the right format, it will not be merged and marked as invalid.
> Kindly adhere to the rules.
> Don't make any changes to the folders in the repo unless you want to add a new folder for the missing topic.

Sure. I will keep in mind and will make the changes in the file.

**Comment by AakashBelide** [comment]
> 
> 
> Hi can I be assigned please if so, how can I help?

You can check out the readme and adhere to the rules to contribute. You need not be assigned to contribute.

**Comment by prasathk11** [comment]
I added Catalan number in dynamic programming and finding bridge using Tarjan algorithm kindly please check merge if my problems are useful into the folders
Thanks
