### ISSUE TITLE
Updated rules for making a PR

### ISSUE THREAD

**Issue by AakashBelide** [ISTE-VIT/hacktoberfest-2020#52]
**Kindly mention the following while making a PR:**
Mention the problem type along with the subcategory and the programming language.
_Ex: Data Structures - Trees (C++)_
If the PR is not in the right format, it will not be merged and marked as invalid.
Don't make any changes in the repo format or create new issues without asking the maintainers.
You can make a new folder if a particular topic is missing.
Kindly avoid repeating the algorithms which are already available.

**All your PRs will be marked as invalid if you don't adhere to the rules.**
Keep contributing!!

**Comment by AakashPanda** [comment]
ok
