### ISSUE TITLE
Caesar cipher - encryption algorithm 

### ISSUE THREAD

**Issue by I3han** [ISTE-VIT/hacktoberfest-2020#87]
It is a encryption algorithm that shift each letter in a string by given amount. 
Ex - AAA (if shifting value is 2) -> CCC
     - AZz Ba (if shifting value is 2) -> CBb Dc
I'm going to build a code from java, Which folder should I add this algorithm?

**Comment by AakashBelide** [comment]
You can make a new folder with the name "Encryption Algorithm" and keep it under Java.
